version: '3.7'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-php
    ports: ['9000:9000']
    volumes:
      - './symfony/:/var/www/symfony:rw'
    environment:
      APP_ENV: dev
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
  nginx:
    build: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    ports: ['8080:80']
    volumes: ['./symfony/:/var/www/symfony']
    depends_on:
      - php